/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hiro

import org.junit.jupiter.api.Test

class LibraryTest {
  @Test
  fun testSomeLibraryMethod() {
    val classUnderTest = Library()
  }
}
